# Generated by Django 4.2.17 on 2024-12-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='recipe',
            new_name='recipetype',
        ),
    ]
